apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
spec:
  selector:
    app: my-app
  ports:
    - name: nginx-container
      protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort