apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
  labels:
    app: multitool-b

spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-b
  template:
    metadata:
      labels:
        app: multitool-b
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        volumeMounts:
          - name: pvc-nfs
            mountPath: /111
        env:
        - name: HTTP_PORT
          value: "80"
        ports:
          - containerPort: 80
            name: http-port
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs

