---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

vector_home: "/opt/vector/"

dummy_logs_type: "my_demo_logs"
parse_logs_type: "my_remap"
